config/routes.rb
Wikiful::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "categories/index"
  get "categories/show"
  get "welcome/index"

  root 'welcome#index'
  resources :articles
  resources :categories
  resources :users
  resources :sessions

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user

	has_many :article_categories
	has_many :categories, through: :article_categories

	validates :title, presence: true
	validates :content, presence: true
	validates :categories, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :articles
	validates_uniqueness_of :email
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  private
  def get_categories
  	@categories = Category.all.order(:name)
  end

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
  	redirect_to login_url, alert: "You must log in to write a wiki" if current_user.nil?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :authorize, only: [:new]

	def index
		@articles = Article.order(updated_at: :desc).limit(25)
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end

	private
		def article_params
			params.require(:article).permit(:title, :content, :category_ids => [])
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all.order(:name)
  end

  def show
  	@category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_url, notice: "Logged in"
		else
			flash.now.alert = "Email or password is invalid"
			render "new"
		end
	end

  def new
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thanks for signing up!"
		else
			render "new"
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :name, :password, :password_confirmation)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@recent_articles = Article.all.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>This is the index view for Articles</h1>
<% @articles.each do |article| %>
	<div>
		<h3><%= link_to article.title, article %></h3>
		<p>Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
		<p>
			Filed under: <% article.categories.each do |category| %>
										 <%= link_to category.name, category %>&nbsp;
									 <% end %>
		</p>
		<p><%= truncate(article.content, length: 200) %></p>
	</div>
<% end %>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
<% if @article.errors.any? %>
	<div class="error_messages">
		<h2>You're missing some fields</h2>
		<ul>
			<% @article.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>Published <%= @article.created_at.strftime('%b %d, %Y') %></p>
<p>Filed under: <% @article.categories.each do |category| %>
  <%= link_to category.name, category %>&nbsp;<% end %>
</p>
<div><%= @article.content %></div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
	<% @categories.each do |category| %>
			<li><%= link_to category.name, category %></li>
	<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %> Articles</h1>

<ul>
	<% @category.articles.each do |article| %>
		<li><%= link_to article.title, article %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//use.typekit.net/tww2lcm.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body id="<%= params[:controller].parameterize %>_controller">
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <%= link_to "Wikiful", root_path, :class => "brand" %>
	      <div class="session-controls" style="float: right;">
	      	<% if current_user %>
	      		<%= link_to "Log Out", session_path("current"), method: 'delete', :class => 'btn btn-primary btn-mini' %>
	      		Logged in as <%= current_user.email %>.
      		<% else %>
		      	<div class="btn-group">
		      		<%= link_to "Sign Up", signup_path, :class => "btn btn-mini" %>
		      		<%= link_to "Log In", login_path, :class => "btn btn-mini" %>
		      	</div>
	      	<% end %>
	      </div>
	    </div>
	  </div>
	</div>

	<div class="container">
		<div class="row">
		  <div class="span4">
		    <% flash.each do |name, msg| %>
		      <%= content_tag :div, msg, id: "flash_#{name}" %>
		    <% end %>
		  </div>
		</div>
		<div class="row">
			<div class="span3">
				<p><%= link_to "Write a Wiki", new_article_path, :class => "btn btn-large" %></p>
				<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames.</p>
				<h3>Categories</h3>
				<ul>
		      <% @categories.each do |category| %>
		        <li><%= link_to category.name, category %></li>
		      <% end %>
		    </ul>
			</div>
			<div class="span8 offset1">
				<%= yield %>
			</div>
		</div>
	</div>


</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class='field'>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class='field'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class='field'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<% @recent_articles.each do |article| %>
	<article class="article_excerpts">
		<p class="article_date">
			<%= article.created_at.strftime('%b %d, %Y') %>&nbsp; &nbsp; -
			<% article.categories.each do |category| %>
				<span class="article_categories"><%= link_to category.name, category %></span>
		  <% end %>
	  </p>
	  <h2 class="article_title"><%= link_to article.title, article %></h2>
	  <p><%= truncate(article.content, length: 300) %></p>
	</article>
<% end %>